In [1]:
%load_ext autoreload
%autoreload 2

In [22]:
from linear_models import LinearRegressor, LogisticRegression
import numpy as np

In [23]:
reg = LinearRegressor()

In [10]:
reg.W = np.array([1, 1])

In [24]:
X = np.array([[2, 3], [3, 2]])

In [25]:
y = [3, 4]

In [26]:
y_true = np.array([6, 6])

In [29]:
reg.score(X, y_true)

6.5000027080432154

In [27]:
reg.fit(X, y)

In [28]:
reg.W

array([ 1.19999916,  0.20000057])

In [30]:
y_pred = reg.predict(X)


In [31]:
y_pred

array([ 3.00000002,  3.99999862])

In [32]:
clf = LogisticRegression()

In [33]:
X = np.array([[-2, -3, -1], [3, 2, 4]])

In [34]:
y = np.array([0, 1])

In [35]:
clf.fit(X, y)

In [36]:
clf.W

array([ 0.8078894 ,  0.95904617,  0.65673263])

In [37]:
clf.predict(X)

array([ 0.,  1.])