In [1]:
%load_ext autoreload
%autoreload 2

In [4]:
from linear_models import LinearRegressor, LogisticRegression
import numpy as np

In [97]:
reg = LinearRegressor()

In [10]:
reg.W = np.array([1, 1])

In [98]:
X = np.array([[2, 3], [3, 2]])

In [99]:
y = [3, 4]

In [23]:
y_true = np.array([6, 6])

In [95]:
reg.score(X, y_true)

12.999748963442157

In [100]:
reg.fit(X, y)

In [101]:
reg.W

array([ 1.19999799,  0.20000135])

In [102]:
y_pred = reg.predict(X)


In [103]:
y_pred

array([ 3.00000002,  3.99999666])

In [5]:
clf = LogisticRegression()

In [13]:
X = np.array([[-2, -3, -1], [3, 2, 4]])

In [7]:
y = np.array([0, 1])

In [14]:
clf.fit(X, y)

In [15]:
clf.W

array([ 0.8078894 ,  0.95904617,  0.65673263])

In [25]:
clf.predict(X)

array([ 0.,  1.])