In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
from linear_models import LinearRegressor, LogisticRegression, SVM
import numpy as np

In [23]:
reg = LinearRegressor()

In [10]:
reg.W = np.array([1, 1])

In [5]:
X = np.array([[2, 3], [3, 2]])

In [6]:
y = [3, 4]

In [7]:
y_true = np.array([6, 6])

In [29]:
reg.score(X, y_true)

6.5000027080432154

In [27]:
reg.fit(X, y)

In [28]:
reg.W

array([ 1.19999916,  0.20000057])

In [30]:
y_pred = reg.predict(X)


In [31]:
y_pred

array([ 3.00000002,  3.99999862])

In [71]:
clf = LogisticRegression(max_epochs=100000)

In [72]:
X = np.array([[-2, -3, -1], [3, 2, 4]])

In [73]:
y = np.array([0, 1])

In [74]:
clf.fit(X, y)

In [75]:
clf.W

array([ 0.20955813,  0.22917987,  0.18993638])

In [76]:
clf.predict(X)

[ 0.21473909  0.86374856]


array([ 0.,  1.])

In [4]:
svm = SVM()

In [11]:
svm.fit(X, y)

In [12]:
svm.W

array([[-0.11198524, -0.11198524, -0.11198524,  0.05340488,  0.28255086],
       [-0.11198524, -0.11198524, -0.11198524,  0.28255086,  0.05340488]])

In [14]:
svm.predict(X)

array([3, 4])

In [15]:
svm.score(X, y)

AttributeError: 'list' object has no attribute 'ndim'