In [2]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
from linear_models import LinearRegressor, LogisticRegression, SVM
import numpy as np

In [4]:
reg = LinearRegressor()

In [5]:
reg.W = np.array([1, 1])

In [6]:
X = np.array([[2, 3], [3, 2]])

In [7]:
y = [3, 4]

In [8]:
y_true = np.array([6, 6])

In [9]:
reg.score(X, y_true)

1.0

In [10]:
reg.fit(X, y)

In [11]:
reg.W

array([ 1.19999965,  0.20000051])

In [12]:
y_pred = reg.predict(X)

In [13]:
y_pred

array([ 3.00000083,  3.99999997])

In [14]:
clf = LogisticRegression(max_epochs=100000)

In [4]:
X = np.array([[-2, -3, -1, 1, 1, 1, 1], [3, 2, 4, 1, 1, 1, 1]])

In [35]:
y = np.array([0, 1])

In [17]:
clf.fit(X, y)

In [18]:
clf.W

array([ 0.20955813,  0.22917987,  0.18993638])

In [19]:
clf.predict(X)

array([ 0.,  1.])

In [20]:
svm = SVM()

In [21]:
svm.fit(X, y)

In [22]:
svm.W

array([[-0.13769161,  0.13769161],
       [-0.15499318,  0.15499318],
       [-0.12039005,  0.12039005]])

In [23]:
svm.predict(X)

array([0, 1])

In [24]:
svm.score(X, y)

1.0

In [156]:
from tree import DecisionTreeClassifier

In [157]:
clf = DecisionTreeClassifier(max_samples=1)

In [158]:
clf.fit(X, y)

In [159]:
clf.predict(X)

array([0, 1])

In [160]:
clf.root.feature, clf.root.threshold

(0, -2)

In [163]:
clf.root.right.label, clf.root.left.label

(1, 0)

In [28]:
from tree import RandomForestClassifier

In [29]:
clf = RandomForestClassifier()

In [36]:
clf.fit(X, y)    

In [37]:
clf.predict(X)

[[0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]]


array([ 0.,  0.])

In [63]:
from clustering import KMeans
kmeans = KMeans(3)

In [64]:
X = np.array([[1, 2, 3], [1, 2, 4], [1, 2, 5], [4, 1, 3], [-2, 2, 3], [19, -2, 3], [1, 2, 3], [1, 2, 3]])

In [67]:
kmeans.fit(X)

[[-2  2  3]
 [ 1  2  5]
 [ 1  2  3]]


In [68]:
kmeans.predict(X)

array([1, 1, 1, 1, 0, 2, 1, 1])

In [69]:
kmeans.centroids

array([[-2,  2,  3],
       [ 1,  1,  3],
       [19, -2,  3]])